# Generated by Django 5.2.1 on 2025-05-17 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("PF", "Pessoa Física"), ("PJ", "Pessoa Jurídica")],
                        default="PJ",
                        max_length=2,
                    ),
                ),
                ("cnpj_cpf", models.CharField(max_length=14, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("telefone", models.CharField(blank=True, max_length=20)),
                ("endereco", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(max_length=20, unique=True, verbose_name="Número"),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Número do Documento",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("NF", "Nota Fiscal"),
                            ("NFS", "Nota Fiscal de Serviço"),
                            ("NFSA", "Nota Fiscal de Serviço Avulsa"),
                            ("REC", "Recibo"),
                            ("FAT", "Fatura"),
                        ],
                        max_length=4,
                        verbose_name="Tipo",
                    ),
                ),
                ("data_documento", models.DateField(verbose_name="Data do Documento")),
                (
                    "data_pagamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Pagamento"
                    ),
                ),
                ("data_entrada", models.DateTimeField(auto_now_add=True)),
                (
                    "valor_documento",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor Bruto"
                    ),
                ),
                (
                    "valor_irrf",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Valor IRRF",
                    ),
                ),
                (
                    "valor_iss",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Valor ISS",
                    ),
                ),
                (
                    "valor_liquido",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor Líquido"
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PEN", "Pendente"),
                            ("PAG", "Pago"),
                            ("ATR", "Atrasado"),
                        ],
                        default="PEN",
                        max_length=3,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_baixa",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Baixa"
                    ),
                ),
                (
                    "secretaria",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ADM", "Sec. de Administração"),
                            ("ASS", "Sec. de Assistência"),
                            ("EDU", "Sec. de Educação"),
                            ("SAU", "Sec. de Saúde"),
                        ],
                        max_length=3,
                        null=True,
                        verbose_name="Secretaria",
                    ),
                ),
                (
                    "recurso",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FUNDEB", "FUNDEB"),
                            ("DMDE", "DMDE"),
                            ("QSE", "QSE"),
                            ("PNAE", "PNAE"),
                            ("PETE", "PETE"),
                            ("PEAE", "PEAE"),
                            ("PNAT", "PNAT"),
                            ("SEDUC_CRECHE", "SEDUC/CRECHE"),
                            ("MOJU_EDUCA", "MOJU-EDUCA"),
                            ("BRALF", "BRALF"),
                            ("PDDE", "PDDE"),
                            ("CONVENIO_EDU", "CONVÊNIO"),
                            ("GABINETE", "GABINETE"),
                            ("PREFEITURA", "PREFEITURA"),
                            ("SEMAD", "SEMAD"),
                            ("SEOB", "SEOB"),
                            ("SECTEMA", "SECTEMA"),
                            ("ILUM_PUBLICA", "ILUM. PÚBLICA"),
                            ("SEMUSP", "SEMUSP"),
                            ("SEMAGRI", "SEMAGRI"),
                            ("LEI_ALDIR_BLANC", "LEI ALDIR BLANC"),
                            ("SECULT", "SECULT"),
                            ("SEMAPI", "SEMAPI"),
                            ("SETRANS", "SETRANS"),
                            ("SEMDESTRE", "SEMDESTRE"),
                            ("SEFAZ", "SEFAZ"),
                            ("SECDELT", "SECDELT"),
                            ("CONVENIO_ADM", "CONVÊNIO"),
                            ("FMAS", "FMAS"),
                            ("IGD_IGPAB", "IGD/IGPAB"),
                            ("PSB", "PSB"),
                            ("MAC", "MAC"),
                            ("GSUAS", "GSUAS"),
                            ("PROT_ESPECIAL", "PROT_ESPECIAL"),
                            ("PROT_BASICA", "PROT_BASICA"),
                            ("BL_IGD", "BL IGD"),
                            ("PROCAD_SUAS", "PROCAD-SUAS"),
                            ("CRIAN_FELIZ", "CRIAN_FELIZ"),
                            ("AUX_BRASIL", "AUX_BRASIL"),
                            ("CONVENIO_ASS", "CONVÊNIO"),
                            ("PISO_ENFER", "PISO ENFER"),
                            ("CONTRAPARTIDA", "CONTRAPARTIDA"),
                            ("FUS", "FUS"),
                            ("OUTROS", "OUTROS"),
                            ("CONVENIO_SAU", "CONVÊNIO"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Recurso",
                    ),
                ),
                (
                    "baixado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_baixados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="documentos.fornecedor",
                        verbose_name="Fornecedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
                "ordering": ["-data_documento"],
                "permissions": [
                    ("dar_baixa_documento", "Pode dar baixa em documentos")
                ],
            },
        ),
    ]
