# Generated by Django 5.2.1 on 2025-05-18 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documentos", "0001_initial"),
        ("fornecedores", "0002_alter_fornecedor_cnpj_cpf_alter_fornecedor_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documento",
            name="fornecedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="fornecedores.fornecedor",
                verbose_name="Fornecedor",
            ),
        ),
        migrations.DeleteModel(
            name="Fornecedor",
        ),
    ]
