# Generated by Django 5.2.1 on 2025-05-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documentos", "0002_alter_documento_fornecedor_delete_fornecedor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("NF", "Nota Fiscal"),
                    ("NFS", "Nota Fiscal de Serviço"),
                    ("NFSA", "Nota Fiscal de Serviço Avulsa"),
                    ("FAT", "Fatura"),
                    ("REC", "Recibo"),
                ],
                max_length=4,
                verbose_name="Tipo",
            ),
        ),
    ]
