# Generated by Django 4.2.23 on 2025-11-05 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documentos', '0004_secretaria_recurso_alter_documento_recurso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='etapa',
            field=models.CharField(choices=[('ABERTURA', 'Abertura de Processo'), ('CONTROLE_INTERNO', 'Controle Interno'), ('EMPENHO', 'Empenho'), ('PAGAMENTO', 'Pagamento'), ('BAIXA', 'Baixa')], default='ABERTURA', max_length=20, verbose_name='Etapa do Processo'),
        ),
        migrations.CreateModel(
            name='HistoricoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('ABERTURA', 'Abertura de Processo'), ('CONTROLE_INTERNO', 'Controle Interno'), ('EMPENHO', 'Empenho'), ('PAGAMENTO', 'Pagamento'), ('BAIXA', 'Baixa')], max_length=20)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='documentos.documento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Documento',
                'verbose_name_plural': 'Históricos de Documento',
                'ordering': ['-data_hora'],
            },
        ),
    ]
