# Generated by Django 5.2.1 on 2025-05-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fornecedores", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fornecedor",
            name="cnpj_cpf",
            field=models.CharField(max_length=14, unique=True, verbose_name="CNPJ/CPF"),
        ),
        migrations.AlterField(
            model_name="fornecedor",
            name="nome",
            field=models.CharField(max_length=200, verbose_name="Nome"),
        ),
    ]
