# Generated by Django 5.2.1 on 2025-05-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fornecedores", "0002_alter_fornecedor_cnpj_cpf_alter_fornecedor_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fornecedor",
            name="endereco",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Endereço"
            ),
        ),
    ]
