# Generated by Django 5.2.1 on 2025-05-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fornecedores", "0003_alter_fornecedor_endereco"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fornecedor",
            name="endereco",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Endereço"
            ),
        ),
    ]
