# Generated by Django 5.2.1 on 2025-05-28 23:50

import fornecedores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0004_alter_fornecedor_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='agencia',
            field=models.CharField(blank=True, help_text='Formato: 0000 ou 0000-0', max_length=6, null=True, verbose_name='Agência'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='conta',
            field=models.CharField(blank=True, help_text='Formato: 0000000000-0', max_length=12, null=True, verbose_name='Conta'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='tipo_conta',
            field=models.CharField(blank=True, choices=[('CC', 'Conta Corrente'), ('PP', 'Poupança')], max_length=2, null=True, verbose_name='Tipo de Conta'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj_cpf',
            field=models.CharField(max_length=14, unique=True, validators=[fornecedores.models.validate_cnpj_cpf], verbose_name='CNPJ/CPF'),
        ),
    ]
