# Generated by Django 5.2.1 on 2026-01-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0005_fornecedor_agencia_fornecedor_banco_fornecedor_conta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='agencia',
            field=models.CharField(blank=True, help_text='Formato: 0000 ou 0000-0 (dígito pode ser X)', max_length=6, null=True, verbose_name='Agência'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='conta',
            field=models.CharField(blank=True, help_text='Formato: 0000000000-0 (dígito pode ser X)', max_length=12, null=True, verbose_name='Conta'),
        ),
    ]
