# Generated by Django 5.2 on 2025-05-10 19:24

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="ativo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="perfil",
            name="data_criacao",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 5, 10, 19, 24, 43, 592064, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="perfil",
            name="token_ativacao",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
