# Generated by Django 5.2 on 2025-05-10 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0002_perfil_ativo_perfil_data_criacao_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perfil",
            name="data_criacao",
        ),
        migrations.AddField(
            model_name="perfil",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente de Aprovação"),
                    ("aprovado", "Aprovado"),
                    ("rejeitado", "Rejeitado"),
                ],
                default="pendente",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="foto",
            field=models.ImageField(default="default.jpg", upload_to="fotos_perfil"),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="usuario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perfil",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
