# Generated by Django 5.2 on 2025-05-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0005_remove_logatividade_ip_remove_perfil_ativo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="logatividade",
            name="ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
