# Generated by Django 5.2.1 on 2025-05-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0006_logatividade_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="data_token",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
